const FONT_SIZE = 12;

const OFFSET_X = 25;

const OFFSET_Y = 25;

const SHIFT = 25;

const BLUE = '#302D4A';
const BLACK = '#302D4A';
const ROOM_COLOR = '#F8FAFF';
const ROOM_COLOR2 = '#F1F9FF';
const WHITE = '#fff';

const FURNITURE_COLOR = '#0051F8';
const CUPBOARD_COLOR = BLACK;
const WINDOW_COLOR = '#0051F8';
const DOOR_COLOR = BLUE;
const WALL_COLOR = BLACK;
const WALL_DOUBLING_COLOR = '#F0F0F0';
const FONT_COLOR = BLACK;

const OUTER_WALL_WIDTH = 0.2;
const INNER_WALL_WIDTH = 0.072;
const WALL_DOUBLING_WIDTH = 0.1;
const WINDOW_WIDTH = 0.5;
const DOOR_WIDTH = 0.08;
const INNER_DOOR_WIDTH = 0.04;
const DOOR_DASH_WIDTH = 0.1;
const DOOR_DASH_SIZE = 0.04;
const CUPBOARD_WIDTH = 0.5;
const CUPBOARD_DASH_SIZE = 3;
const GARAGE_DASH_SIZE = 3;
const WINDOW_DASH_SIZE = 4;

const ROOM_COLORS = {
    'Salon': ROOM_COLOR,
    'Hall': ROOM_COLOR,
    'Cuisine': ROOM_COLOR,
    'Salle de Bain': ROOM_COLOR,
    'WC': ROOM_COLOR,
    'Chambre 1': ROOM_COLOR,
    'Chambre 2': ROOM_COLOR,
    'Chambre 3': ROOM_COLOR,
    "Dégagement": ROOM_COLOR,
    'Chambre 4': ROOM_COLOR,
    'Chambre 5': ROOM_COLOR,
    'Dressing': ROOM_COLOR,
    "Salle d'eau": ROOM_COLOR,
    "Placard 1": ROOM_COLOR,
    "trouL": 'green',
    "Placard 2": ROOM_COLOR,
    "Placard 3": ROOM_COLOR,
    "Placard 4": ROOM_COLOR,
    "Placard 5": ROOM_COLOR,
    "Cellier": ROOM_COLOR,
    "Buanderie": ROOM_COLOR,
    'Garage': ROOM_COLOR
};

// Picture size for furniture

const BATHROOM_HEIGHT = 700;
const SHOWER_HEIGHT = 900;
const SINK_HEIGHT = 600;
const SINK_WIDTH = 400;
const WC_HEIGHT = 700;
const KITCHEN_SINK_HEIGHT = 500;
const BED_HEIGHT = 2000;

const KITCHEN_TABLE_HEIGHT = 2.1;
const KITCHEN_TABLE_WIDTH = 1.4;

const WORKPLAN_KITCHEN_HEIGHT = 0.6;

const HUMAN_SPACE = 0.8;


export { FONT_SIZE, HUMAN_SPACE, KITCHEN_TABLE_HEIGHT, KITCHEN_TABLE_WIDTH, CUPBOARD_COLOR, WALL_DOUBLING_WIDTH, WALL_DOUBLING_COLOR, FURNITURE_COLOR, DOOR_DASH_WIDTH, DOOR_DASH_SIZE, INNER_DOOR_WIDTH, BATHROOM_HEIGHT, BED_HEIGHT, KITCHEN_SINK_HEIGHT, WORKPLAN_KITCHEN_HEIGHT, WC_HEIGHT, SINK_HEIGHT, SINK_WIDTH, SHOWER_HEIGHT, CUPBOARD_DASH_SIZE, CUPBOARD_WIDTH, WINDOW_DASH_SIZE, ROOM_COLORS,GARAGE_DASH_SIZE, OFFSET_X, FONT_COLOR, OFFSET_Y, SHIFT, WINDOW_COLOR, DOOR_COLOR,WALL_COLOR, OUTER_WALL_WIDTH, INNER_WALL_WIDTH, WINDOW_WIDTH, DOOR_WIDTH };
